### ISSUE TITLE
clinical information

### ISSUE THREAD

**Issue by geek-APTX4869** [RichardSunnyMeng/MSMFN#1]
Dear author：
  如何输入临床信息？

**Comment by RichardSunnyMeng** [comment]
Hi~ You can use the model _IndividualModel_ (Line 168 in models/model.py). The clinical information can be input into it as _clinical_ in _IndividualModel.forward()_. Maybe you need to modify its fc layers and the input formats according to your data.

**Comment by RichardSunnyMeng** [comment]
> Hi~ You can use the model _IndividualModel_ (Line 168 in models/model.py). The clinical information can be input into it as _clinical_ in _IndividualModel.forward()_. Maybe you need to modify its fc layers and the input formats according to your data.

Besides, some preprocessing methods are necessary, such as normalization. It can be seen in our paper.
